### ISSUE TITLE
Data storage: Explore relevance of Project Drive

### ISSUE THREAD

**Issue by jurra** [fvanoorschot/global_sr_module#2]
# Request project drive
Considerations of the request: https://tu-delft-dcc.github.io/02_Data/03_Storage/01_ProjectDrive_request.html?highlight=project%20drive

Can we estimate how much data are we working with?

**Comment by jurra** [comment]
Hi @fvanoorschot I think this one we can close since we have now a project drive correct?

**Comment by fvanoorschot** [comment]
yes
