### ISSUE TITLE
Environment issue to be documented, multiple environments

### ISSUE THREAD

**Issue by jurra** [fvanoorschot/global_sr_module#6]
Currently we use different environments to perform the tasks.

1. Are there package incompatibilities that force us to use different environments, 
2. or can we have all dependencies in one environment?

If 2 then we might need to create a bash scripts where this different jobs are done, including activating the specific environment for task a and the deactivating it to perform task b

**Comment by fvanoorschot** [comment]
1. Yes, the earthengine-api package is not compatible (https://developers.google.com/earth-engine/guides/python_install-conda) with the ewatercycle environment (https://ewatercycle.readthedocs.io/en/latest/system_setup.html#conda-environment)
2. No, we need 2 separate environments.

The packages in the two environments used are listed in the attached txt files:

[conda_list_ee_env.txt](https://github.com/fvanoorschot/global_sr_module/files/8260354/conda_list_ee_env.txt)
[conda_list_ewatercycle_env.txt](https://github.com/fvanoorschot/global_sr_module/files/8260355/conda_list_ewatercycle_env.txt)

**Comment by fvanoorschot** [comment]
1. No, we can have all packages in one environment. I installed the environment from https://ewatercycle.readthedocs.io/en/latest/system_setup.html#conda-environment and I added the earthengine-api package myself (https://developers.google.com/earth-engine/guides/python_install-conda)
2. Yes

The only problem with this environment is its linux dependence. The esmvaltool-python package cannot be installed on windows.

The conda list of packages can be found here:
[conda_list_env.txt](https://github.com/fvanoorschot/global_sr_module/files/8260457/conda_list_env.txt)

**Comment by jurra** [comment]
Great @fvanoorschot then we can close this issue. Lets focus on linux for now to make it simple, since the target is to work on a cluster that is linux ;)
